language: python
python:
  - "3.6"
  - "3.7"
install: "pip install -r requirements.txt -r requirements-dev.txt"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - python manage.py collectstatic
script:
  - black --check app --check user
  - pytest --cov=app --cov=user --cov-report xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVISpyte_TEST_RESULT